### PR TITLE
Fix errors when specifying params

### LINKED ISSUE #7: POST /modules/{id} Failing
Screen Shot 2019-09-05 at 8 07 44 PM

### PR DESCRIPTION
**Pull request by wmedrano**
Fixes #7

### CODE REVIEW

File: server/src/endpoint.rs [hunk 1]
```diff
@@ -178,34 +179,35 @@ impl wdaw_api::Server for Server {
...
+            .ok_or_else(|| schemas::Error::new("no plugin specified"))?
+            .clone();
+        let plugin_id = uri_to_id("/plugins/", &plugin_uri)?;
         let mut module = module;
         if module.params.is_none() {
             let maybe_params = self
                 .params
                 .plugins
                 .metadata_iter()
-                .find(|m| m.id == module_id)
```
Comment (wmedrano) [inline server/src/endpoint.rs]: This was the issue.

We were looking for the metadata for a plugin by using the module_id instead of the plugin_id.

TODO: have different types for the different ID spaces.

Comment (wmedrano) [reply server/src/endpoint.rs]: This caused params to be None instead of Some(obj).

Downstream this is (if I remember correctly)
1. Encoded as a JSON string again
2. Decoded to the plugin's  special data structure (failed here)
3. Encoded to a binary Vec<u8> that can be passed to the main processing channel.

File: engine/src/error.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
+use crate::Id;
+use std::fmt;
+
+#[derive(Clone, Debug)]
+pub enum Error {
+    PluginNotFound(Id),
+    PluginAlreadyExists(Id),
+    ParamsNotJsonObject(String),
```
Comment (helenmedrano) [inline engine/src/error.rs]: 👍
